<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_L_option-label-color-93-item-50</name>
   <tag></tag>
   <elementGuidId>61db9b56-86c0-4577-a6e7-a02e04229bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-label-color-93-item-50</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='option-label-color-93-item-50']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd35fd51-2e86-47e1-a390-f7b62a1ac385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option color</value>
      <webElementGuid>2e27ca7c-f1c2-481c-a456-23cdb7de1ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-color-93-item-50</value>
      <webElementGuid>20d065fd-46e4-481c-ad9d-a96ead52974e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b9efceff-1622-4bc1-9fdd-5c966323fbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bbd1699c-7b32-4613-a29f-a7c41f6506e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-color-93</value>
      <webElementGuid>47f08ebb-1023-4d4d-a380-5da264cd817c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c5f8dca-458d-4806-ab26-39ee73196fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6d5fcd32-bc5f-4343-89b0-4f261ecdeb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-id</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9d0d8b06-87d9-4382-81d0-9ae0d2a5a9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-label</name>
      <type>Main</type>
      <value>Blue</value>
      <webElementGuid>dcb18cbc-a90a-4c81-9bf4-537b677854bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Blue</value>
      <webElementGuid>2fc082eb-555b-45ad-a0d5-543ff53c69ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b7f1a2db-5c25-4df2-baa9-860eb6c287f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>16b56012-206c-4ad3-a34b-97f80472b7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>af80e99e-93eb-41d1-965c-3fe4f34803c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-tooltip-value</name>
      <type>Main</type>
      <value>#1857f7</value>
      <webElementGuid>fc2e60fa-f516-4f50-905d-6cc341883005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-item-info_1226&quot;)/div[@class=&quot;product details product-item-details&quot;]/div[@class=&quot;swatch-opt-1226&quot;]/div[@class=&quot;swatch-attribute color&quot;]/div[@class=&quot;swatch-attribute-options clearfix&quot;]/div[@id=&quot;option-label-color-93-item-50&quot;]</value>
      <webElementGuid>8b4fa513-92c6-4f13-bec1-c2283eb9d2e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='option-label-color-93-item-50']</value>
      <webElementGuid>a1371a4e-b76b-4083-abce-a59c5aa809c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-item-info_1226']/div/div[3]/div[2]/div/div</value>
      <webElementGuid>ae45b31b-aa47-4206-aeab-e77447991606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div[2]/div/div</value>
      <webElementGuid>e8f4542d-a942-408d-8e7e-2ee2073b37d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-color-93-item-50']</value>
      <webElementGuid>5d4dc5f1-72a2-47e5-b92f-af0cd5781bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
