<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Color_swatch-option color</name>
   <tag></tag>
   <elementGuidId>863ece78-70ba-426f-8aa7-951a3d1c347f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='narrow-by-list']/div[3]/div[2]/div/div/a[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8831cd2-43c7-4430-8d46-40826c6a47f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option color </value>
      <webElementGuid>598b9b67-9632-4981-9e96-3d944c8f0e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>97a9f8f8-cda0-4ae9-886b-c2d43e3cb67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>685685af-6625-4127-9325-5123eb696503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-id</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>75e5a1ca-6c66-4dbc-abbf-d20d96a7ffe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-label</name>
      <type>Main</type>
      <value>Blue</value>
      <webElementGuid>36de0cb2-1e1f-47c1-90a4-02e219cea60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-tooltip-value</name>
      <type>Main</type>
      <value>#1857f7</value>
      <webElementGuid>0f6e30fc-bc0d-4e05-9ba6-13ce4c350f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;narrow-by-list&quot;)/div[@class=&quot;filter-options-item allow active&quot;]/div[@class=&quot;filter-options-content&quot;]/div[@class=&quot;swatch-attribute swatch-layered color&quot;]/div[@class=&quot;swatch-attribute-options clearfix&quot;]/a[@class=&quot;swatch-option-link-layered&quot;]/div[@class=&quot;swatch-option color&quot;]</value>
      <webElementGuid>8e507308-fea6-4fb7-8107-c17f436ff665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='narrow-by-list']/div[3]/div[2]/div/div/a[2]/div</value>
      <webElementGuid>27ef2bad-a811-420c-bc24-f7dc22158695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::div[5]</value>
      <webElementGuid>0879fbfc-996d-472c-a20b-f0827afce4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='item'])[3]/following::div[7]</value>
      <webElementGuid>87d29409-b3d5-4f4f-ae3b-193ea7726086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[1]/preceding::div[7]</value>
      <webElementGuid>2216158e-b408-491f-a690-5a6fe90bf570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/a[2]/div</value>
      <webElementGuid>cd1522a7-cdb4-487b-bf55-6170e31daef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
