<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Set Descending Direction_product-image-photo</name>
   <tag></tag>
   <elementGuidId>c21ad416-23ed-48ba-846a-7b5c73ea99fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.product-image-photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>69b47bce-e691-46e7-8371-ee515b874dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>57422e26-ff57-466c-8176-1a246194fdae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento-demo.mageplaza.com/media/catalog/product/cache/640d160c8b47be2cb09be947679534b3/w/j/wj01-red_main_1.jpg</value>
      <webElementGuid>5f15f8c3-bc1b-4b3a-936e-f37a4d775912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>dad5ed7d-b487-4571-a4fe-c0e93fae61d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>51ae09be-7b0f-4a99-91d4-7c38d39eda21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>70c7010b-77e7-4d77-a3d7-e0e5ddff646e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Stellar Solar Jacket</value>
      <webElementGuid>165dd069-cef3-4e13-b83f-e6c894bd18cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-item-info_1226&quot;)/a[@class=&quot;product photo product-item-photo&quot;]/span[@class=&quot;product-image-container product-image-container-1226&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>a7a8f682-79e5-45ad-aa3a-fdd054170911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-item-info_1226']/a/span/span/img</value>
      <webElementGuid>a4ac808f-c176-4099-bd19-bd7779655756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Stellar Solar Jacket']</value>
      <webElementGuid>59844642-bd2d-48b9-a836-8bda43627a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>cdb29780-79cf-492b-8e99-b8b1ea127f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento-demo.mageplaza.com/media/catalog/product/cache/640d160c8b47be2cb09be947679534b3/w/j/wj01-red_main_1.jpg' and @alt = 'Stellar Solar Jacket']</value>
      <webElementGuid>a8a19c19-4803-441c-a0c9-03b0e323971a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
