<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Style</name>
   <tag></tag>
   <elementGuidId>f4638d0c-acaa-4c44-be6d-0418379567e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layered-filter-block']/div[2]/div/ol/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.filter-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>704a525f-57ba-4b7a-8af9-b4277d18be43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-label</value>
      <webElementGuid>c35ffbdc-e5af-4d8f-aea3-5a611f919066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Style</value>
      <webElementGuid>15704f38-f195-4f40-b2b6-eb50747ce7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layered-filter-block&quot;)/div[@class=&quot;block-content filter-content&quot;]/div[@class=&quot;filter-current&quot;]/ol[@class=&quot;items&quot;]/li[@class=&quot;item&quot;]/span[@class=&quot;filter-label&quot;]</value>
      <webElementGuid>750eb045-c0f9-4129-986c-3a3565b3cd01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layered-filter-block']/div[2]/div/ol/li/span</value>
      <webElementGuid>2f5eadff-1f34-4890-98d6-8524eec64a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Now Shopping by'])[1]/following::span[1]</value>
      <webElementGuid>6a1a53e8-19d3-4bf6-b122-bf345e4e9788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop By'])[1]/following::span[1]</value>
      <webElementGuid>0eefe4a8-0fc5-4a01-8d00-20fb27016138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insulated'])[1]/preceding::span[1]</value>
      <webElementGuid>32fbc3b6-abee-4e29-89f0-2f89a3e37b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove This Item'])[1]/preceding::span[2]</value>
      <webElementGuid>14c89b66-c3f5-4d07-b1d6-6316dd44aa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Style']/parent::*</value>
      <webElementGuid>08d9cbfa-a253-46d0-828e-bab3c66347cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/span</value>
      <webElementGuid>089a316e-ecf6-4687-8c6f-b55784466729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Style' or . = 'Style')]</value>
      <webElementGuid>4ff23f9a-cd9a-4e9a-b887-12f0acdd7e61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
