<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Compare</name>
   <tag></tag>
   <elementGuidId>ca3a7639-3479-4980-9e4c-bd48b415e0e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[3]/div[3]/div/div[2]/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.action.compare.primary > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9c1b78e-038f-4939-8b87-b2eb16b16e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare</value>
      <webElementGuid>bf0d1673-fa96-430f-a323-d3fc7d8c1102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;sidebar sidebar-additional&quot;]/div[@class=&quot;block block-compare&quot;]/div[@class=&quot;block-content&quot;]/div[@class=&quot;actions-toolbar&quot;]/div[@class=&quot;primary&quot;]/a[@class=&quot;action compare primary&quot;]/span[1]</value>
      <webElementGuid>4c4c22f4-ae48-4f26-9ea3-7e930a45066b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div[3]/div/div[2]/div/div/a/span</value>
      <webElementGuid>43dff7c1-e5d5-4dd7-9038-883c9e07c5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove This Item'])[2]/following::span[1]</value>
      <webElementGuid>df502788-032a-435b-8f3a-4af89ba96d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Josie Yoga Jacket'])[2]/following::span[2]</value>
      <webElementGuid>ee88c1d7-6149-432f-80a7-f99f198798dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/preceding::span[1]</value>
      <webElementGuid>e16c9217-4ae0-449b-bfef-7dda4a481763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Wish List'])[1]/preceding::span[2]</value>
      <webElementGuid>5b4ee2c4-37a2-4d71-aee6-2cd0a3a15450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compare']/parent::*</value>
      <webElementGuid>53ec7934-e3dc-45b3-bf19-8b72c7a98927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/span</value>
      <webElementGuid>065ab9d0-e08a-4b1a-b51f-d91b2afcde6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Compare' or . = 'Compare')]</value>
      <webElementGuid>b838d932-fa31-4828-a21c-1289f2ff82b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
