<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Compare Products</name>
   <tag></tag>
   <elementGuidId>6afff5d7-84cb-4d3d-b83a-3157bc5199e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#block-compare-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//strong[@id='block-compare-heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>d64512fe-3ada-4b15-880f-d1ecbbfae1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>block-compare-heading</value>
      <webElementGuid>a4ac4a8f-3217-401c-b090-3741b266448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>9c865b91-783c-4a6f-b062-c42e98f4ea56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0dbdbe9a-d9f1-4d56-b4f3-8969246fc82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare Products</value>
      <webElementGuid>0f284c11-ab5f-4619-8192-8727c9c58666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-compare-heading&quot;)</value>
      <webElementGuid>6b6a7dca-d6cf-4bf0-9f91-1d46fab1f2d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='block-compare-heading']</value>
      <webElementGuid>cef67e55-3ecb-40c7-83ed-b505cf11d365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div[3]/div/div/strong</value>
      <webElementGuid>8bf77e5a-e038-4dcc-951f-d82607223de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='item'])[50]/following::strong[1]</value>
      <webElementGuid>d58a659e-a131-4724-a20c-ad0652919a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have no items to compare.'])[1]/preceding::strong[1]</value>
      <webElementGuid>83af9f01-36c5-4fea-9af5-6dd4ace30964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Wish List'])[1]/preceding::strong[1]</value>
      <webElementGuid>34e3200f-5b5d-4f00-a7ef-76901e8975a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/strong</value>
      <webElementGuid>5ec7cac6-090f-45a0-b915-77ee77176e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'block-compare-heading' and (text() = 'Compare Products' or . = 'Compare Products')]</value>
      <webElementGuid>2908f892-3741-44af-8afa-d149200ba30a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
